############## clock define##################
set_property PACKAGE_PIN Y9 [get_ports clk_50m]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50m]
#########################ethernet######################
create_clock -period 8.000 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_txd[*]}]
set_property SLEW FAST [get_ports {rgmii1_txd[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports e1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e1_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e1_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txctl]
set_property SLEW FAST [get_ports rgmii1_txc]
set_property SLEW FAST [get_ports rgmii1_txctl]

set_property PACKAGE_PIN K15 [get_ports {rgmii1_rxd[3]}]
set_property PACKAGE_PIN J15 [get_ports {rgmii1_rxd[2]}]
set_property PACKAGE_PIN K18 [get_ports {rgmii1_rxd[1]}]
set_property PACKAGE_PIN J18 [get_ports {rgmii1_rxd[0]}]
set_property PACKAGE_PIN N20 [get_ports {rgmii1_txd[3]}]
set_property PACKAGE_PIN N19 [get_ports {rgmii1_txd[2]}]
set_property PACKAGE_PIN N18 [get_ports {rgmii1_txd[1]}]
set_property PACKAGE_PIN N17 [get_ports {rgmii1_txd[0]}]
set_property PACKAGE_PIN J17 [get_ports e1_mdc]
set_property PACKAGE_PIN J16 [get_ports e1_mdio]
set_property PACKAGE_PIN L19 [get_ports e1_reset]
set_property PACKAGE_PIN K19 [get_ports rgmii1_rxc]
set_property PACKAGE_PIN K20 [get_ports rgmii1_rxctl]
set_property PACKAGE_PIN R21 [get_ports rgmii1_txc]
set_property PACKAGE_PIN R20 [get_ports rgmii1_txctl]

create_clock -period 8.000 [get_ports rgmii2_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_txd[*]}]
set_property SLEW FAST [get_ports {rgmii2_txd[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports e2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e2_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e2_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txctl]
set_property SLEW FAST [get_ports rgmii2_txc]
set_property SLEW FAST [get_ports rgmii2_txctl]

set_property PACKAGE_PIN M21 [get_ports {rgmii2_rxd[3]}]
set_property PACKAGE_PIN N22 [get_ports {rgmii2_rxd[2]}]
set_property PACKAGE_PIN P22 [get_ports {rgmii2_rxd[1]}]
set_property PACKAGE_PIN P18 [get_ports {rgmii2_rxd[0]}]
set_property PACKAGE_PIN L16 [get_ports {rgmii2_txd[3]}]
set_property PACKAGE_PIN L21 [get_ports {rgmii2_txd[2]}]
set_property PACKAGE_PIN L22 [get_ports {rgmii2_txd[1]}]
set_property PACKAGE_PIN L18 [get_ports {rgmii2_txd[0]}]
set_property PACKAGE_PIN M20 [get_ports e2_mdc]
set_property PACKAGE_PIN T17 [get_ports e2_mdio]
set_property PACKAGE_PIN T16 [get_ports e2_reset]
set_property PACKAGE_PIN M19 [get_ports rgmii2_rxc]
set_property PACKAGE_PIN P17 [get_ports rgmii2_rxctl]
set_property PACKAGE_PIN K16 [get_ports rgmii2_txc]
set_property PACKAGE_PIN M22 [get_ports rgmii2_txctl]
